language: go

install:
- true

go:
- 1.6.2
- 1.7.1
- tip

before_deploy: go build
before_install: cd gorates
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: BGyly08JRBZ/ORJLC5yhmkFbQNp8IbwG3q5Gzq0MBvwURwZh4w6eSPfo5GwNURbE9OCMNISPyltporKuL4SuGz39VS5R0tetOecFuaXGNmCiAHPJlF/WoMkND7NhxAqHvfschxaLbyOITjAJA4DkkO4qT7/5sJ7eFepLyXWN8mxUe9RtAteVhg6T4onyV5iVNxMRTmWd3FUYXZIR9AW9c7paeeYLAF4GQTw7SagYKGJ2L8n/LOxmEpTvurTav9qBOaqHhaOimjtazn9FT1Mv4sZdsCoAvVA68yUIipFfBm+zh2m03pt+rqIBuSMTvWOG1FPIz9Ne9+y+PjkAq+wVO2z0YpQMKIL+MjnYGlIRdW6y1X8Jh7wzv8fd1dqDIkGL1HagBNmAszPbfwkNMr5lHJpq8HSzGpQDFUMUC3zqcT04icX4MblGoyEg6ZPTNmj/e39EvzGoK/ZHtOIbQRJJ5uNAgqk8t7zxND/N/TNduwVWgoIV9+ewtDdF6E5hPgw7Jd5rMJAQsaOsPq7VC8MxZMNo6mwk0/UMAvLSmIBCozus44cLQoNubkQMu5EyzgrRVjJKOi3pTxVuCkdVTNGwjpC1eu0Es1+vBri/rICiF1rLvekoAYLSynnHeh6toABr847PWJYCxfqNZmdH2MEQAixe1TqrW5rVDSxHZmoQ8s4=
  file: gorates
  on:
    tags: true
    condition: $TRAVIS_GO_VERSION = 1.7.1
