version: '3'

services:
  redis:
    image: redis
  euribor:
    build:
      context: .
    environment:
      REDIS_HOST: redis
      DATA_PATH: /mnt/data
    volumes:
      - ${PWD}:/mnt/data
    depends_on:
      - redis
    ports:
      - 127.0.0.1:8080:8080
